Extend websocket server to support message limits and throttling
ignitionrobotics/ign-launch pull request #116
Opened 2021-06-03 04:56 UTC by iche033

## Summary

Added 3 new features:

* setting max msg queue size
    * Msg published to websocket clients can now have a msg queue size limit to prevent the queue from infinitely growing. You can now set this by specifying:
    ```
      <queue_size_per_connection>10</queue_size_per_connection>
    ```
* throttling publish rate for topics
   * Added a keyword `throttle` that can be used by clients to limit the publish rate of a specific topic. This is initiated by the websocket client and it affects all clients who are subscribed to that topic.

* limiting number of subscriptions per msg type
    * some msg types have large message size. So this configuration allows users to limit the number of subscriptions that each connection can open for a particular msg type, e.g. the following limits each client to subscribe to only 1 point cloud topic

    ```
    <subscription_limit_per_connection>
      <subscription>
        <msg_type>ignition.msgs.PointCloudPacked</msg_type>
        <limit>1</limit>
      </subscription>
    </subscription_limit_per_connection>
    ```

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

2021-06-03 07:41 UTC, ahcorde requested changes

2021-06-03 07:41 UTC, ahcorde commented on plugins/websocket_server/WebsocketServer.hh
> +      public: bool UpdateMsgTypeSubscriptionCount(const std::string &_topic,
\return

2021-06-03 22:27 UTC, iche033 commented on plugins/websocket_server/WebsocketServer.hh
> +      public: bool UpdateMsgTypeSubscriptionCount(const std::string &_topic,
ebc1c5eb088827a49e2bbbd9a53f3e00df7466d2

2021-06-09 17:29 UTC, nkoenig approved these changes
One minor comment

2021-06-09 17:29 UTC, nkoenig commented on plugins/websocket_server/WebsocketServer.cc
> +          if (timeDeltaCon > conIt->second->topicPublishPeriods[_info.Topic()])
```suggestion
          if (timeDeltaCon >= conIt->second->topicPublishPeriods[_info.Topic()])
```

2021-06-09 18:31 UTC, merged